/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.assignment1;

import java.awt.Color;
import static java.awt.Color.red;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author s0537470
 */
public class Connect4 extends javax.swing.JFrame {

    private final JButton[][] buttonArray;//sets 2D array 

    /**
     * Creates new form Interface
     */
    public Connect4() {
        initComponents();

        //declaration
        buttonArray = new JButton[8][8];

        //row 0
        buttonArray[0][0] = jButton1;
        buttonArray[0][1] = jButton2;
        buttonArray[0][2] = jButton3;
        buttonArray[0][3] = jButton4;
        buttonArray[0][4] = jButton5;
        buttonArray[0][5] = jButton6;
        buttonArray[0][6] = jButton7;
        buttonArray[0][7] = jButton8;

        //row 1
        buttonArray[1][0] = jButton9;
        buttonArray[1][1] = jButton10;
        buttonArray[1][2] = jButton11;
        buttonArray[1][3] = jButton12;
        buttonArray[1][4] = jButton13;
        buttonArray[1][5] = jButton14;
        buttonArray[1][6] = jButton15;
        buttonArray[1][7] = jButton16;

        //row 2
        buttonArray[2][0] = jButton17;
        buttonArray[2][1] = jButton18;
        buttonArray[2][2] = jButton19;
        buttonArray[2][3] = jButton20;
        buttonArray[2][4] = jButton21;
        buttonArray[2][5] = jButton22;
        buttonArray[2][6] = jButton23;
        buttonArray[2][7] = jButton24;

        //row 3
        buttonArray[3][0] = jButton25;
        buttonArray[3][1] = jButton26;
        buttonArray[3][2] = jButton27;
        buttonArray[3][3] = jButton28;
        buttonArray[3][4] = jButton29;
        buttonArray[3][5] = jButton30;
        buttonArray[3][6] = jButton31;
        buttonArray[3][7] = jButton32;

        //row 4
        buttonArray[4][0] = jButton33;
        buttonArray[4][1] = jButton34;
        buttonArray[4][2] = jButton35;
        buttonArray[4][3] = jButton36;
        buttonArray[4][4] = jButton37;
        buttonArray[4][5] = jButton38;
        buttonArray[4][6] = jButton39;
        buttonArray[4][7] = jButton40;

        //row 5
        buttonArray[5][0] = jButton41;
        buttonArray[5][1] = jButton42;
        buttonArray[5][2] = jButton43;
        buttonArray[5][3] = jButton44;
        buttonArray[5][4] = jButton45;
        buttonArray[5][5] = jButton46;
        buttonArray[5][6] = jButton47;
        buttonArray[5][7] = jButton48;

        //row 6
        buttonArray[6][0] = jButton49;
        buttonArray[6][1] = jButton50;
        buttonArray[6][2] = jButton51;
        buttonArray[6][3] = jButton52;
        buttonArray[6][4] = jButton53;
        buttonArray[6][5] = jButton54;
        buttonArray[6][6] = jButton55;
        buttonArray[6][7] = jButton56;

        //row 7
        buttonArray[7][0] = jButton57;
        buttonArray[7][1] = jButton58;
        buttonArray[7][2] = jButton59;
        buttonArray[7][3] = jButton60;
        buttonArray[7][4] = jButton61;
        buttonArray[7][5] = jButton62;
        buttonArray[7][6] = jButton63;
        buttonArray[7][7] = jButton64;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        topTopPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        playerPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        topPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        topPanel.setAlignmentX(3.0F);
        topPanel.setAlignmentY(3.0F);
        topPanel.setPreferredSize(new java.awt.Dimension(831, 80));
        topPanel.setLayout(new java.awt.GridLayout(1, 1));

        startButton.setText("Start Game");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        topPanel.add(startButton);

        jButton65.setText("Cancel Game");
        jButton65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton65ActionPerformed(evt);
            }
        });
        topPanel.add(jButton65);

        topTopPanel.setLayout(new java.awt.GridLayout(2, 3));

        jLabel3.setText("Player 1");
        topTopPanel.add(jLabel3);

        jLabel2.setText("Player 2");
        topTopPanel.add(jLabel2);

        jLabel1.setText("Player 3");
        topTopPanel.add(jLabel1);

        jComboBox1.setEditable(true);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Red", "Yellow", "Green" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        topTopPanel.add(jComboBox1);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Red", "Yellow", "Green" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        topTopPanel.add(jComboBox2);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Red", "Yellow", "Green" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        topTopPanel.add(jComboBox3);

        topPanel.add(topTopPanel);

        getContentPane().add(topPanel, java.awt.BorderLayout.PAGE_START);

        playerPanel.setLayout(new java.awt.GridLayout(8, 8));

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton1);

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton2);

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton3);

        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton4);

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton5);

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton6);

        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton7);

        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton8);

        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton9);

        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton10);

        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton11);

        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton12);

        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton13);

        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton14);

        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton15);

        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton16);

        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton17);

        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton18);

        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton19);

        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton20);

        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton21);

        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton22);

        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton23);

        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton24);

        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton25);

        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton26);

        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton27);

        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton28);

        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton29);

        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton30);

        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton31);

        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton32);

        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton33);

        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton34);

        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton35);

        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton36);

        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton37);

        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton38);

        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton39);

        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton40);

        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton41);

        jButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton42);

        jButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton43);

        jButton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton44);

        jButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton45);

        jButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton46);

        jButton47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton47);

        jButton48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton48);

        jButton49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton49);

        jButton50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton50);

        jButton51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton51);

        jButton52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton52);

        jButton53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton53);

        jButton54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton54);

        jButton55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton55);

        jButton56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton56);

        jButton57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton57);

        jButton58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton58);

        jButton59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton59);

        jButton60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton60);

        jButton61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton61);

        jButton62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton62);

        jButton63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton63);

        jButton64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerPanel.add(jButton64);

        getContentPane().add(playerPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //gets player color as integers. 1=red, 2=yellow and 3=green
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if (jComboBox1.getSelectedIndex() == 0) {
            p1Color = 1;
        }
        if (jComboBox1.getSelectedIndex() == 1) {
            p1Color = 2;
        }
        if (jComboBox1.getSelectedIndex() == 2) {
            p1Color = 3;
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        if (jComboBox2.getSelectedIndex() == 0) {
            p2Color = 1;
        }
        if (jComboBox2.getSelectedIndex() == 1) {
            p2Color = 2;
        }
        if (jComboBox2.getSelectedIndex() == 2) {
            p2Color = 3;
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        if (jComboBox3.getSelectedIndex() == 0) {
            p3Color = 1;
        }
        if (jComboBox3.getSelectedIndex() == 1) {
            p3Color = 2;
        }
        if (jComboBox3.getSelectedIndex() == 2) {
            p3Color = 3;
        }
    }//GEN-LAST:event_jComboBox3ActionPerformed

    
    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed

        disableButtons();//grid is intitailly disabled
        //if all colors are different if statement runs
        if (jComboBox1.getSelectedIndex() != jComboBox2.getSelectedIndex()
                && jComboBox1.getSelectedIndex() != jComboBox3.getSelectedIndex()
                && jComboBox3.getSelectedIndex() != jComboBox2.getSelectedIndex()) {
            startGame = true;
            enableButtons();//enables grid. disables colors
            disableColorButton();
            startButton.setText("Player 1 Turn");

        } else {
            JOptionPane.showMessageDialog(this, "Error. Matching Colors.");
        }


    }//GEN-LAST:event_startButtonActionPerformed

    //
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JButton thisOne = (JButton) evt.getSource();

        if (startGame == true) {
            if (thisOne.getText().equals("") && (p1 == true)) {
                thisOne.setText("X");
                startButton.setText("Player 2 Turn");
                switch (p1Color) {
                    case 1:
                        thisOne.setBackground(Color.red);
                        thisOne.setForeground(Color.red);
                        break;
                    case 2:
                        thisOne.setBackground(Color.yellow);
                        thisOne.setForeground(Color.yellow);
                        break;
                    case 3:
                        thisOne.setBackground(Color.green);
                        thisOne.setForeground(Color.green);
                        break;
                }
                p1 = false;
                p2 = true;
            } else if (thisOne.getText().equals("") && (p2 == true)) {
                thisOne.setText("O");
                startButton.setText("Player 3 Turn");
                switch (p2Color) {
                    case 1:
                        thisOne.setBackground(Color.red);
                        thisOne.setForeground(Color.red);
                        break;
                    case 2:
                        thisOne.setBackground(Color.yellow);
                        thisOne.setForeground(Color.yellow);
                        break;
                    case 3:
                        thisOne.setBackground(Color.green);
                        thisOne.setForeground(Color.green);
                        break;
                }
                p2 = false;
                p3 = true;
            } else if (thisOne.getText().equals("") && (p3 == true)) {
                thisOne.setText("Y");
                startButton.setText("Player 1 Turn");

                switch (p3Color) {
                    case 1:
                        thisOne.setBackground(Color.red);
                        thisOne.setForeground(Color.red);
                        break;
                    case 2:
                        thisOne.setBackground(Color.yellow);
                        thisOne.setForeground(Color.yellow);
                        break;
                    case 3:
                        thisOne.setBackground(Color.green);
                        thisOne.setForeground(Color.green);
                        break;
                }
                p1 = true;
                p3 = false;
            }

            move++;
            try {
                checkForWin();
            } catch (NoSuchFieldException ex) {
                Logger.getLogger(Connect4.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalArgumentException ex) {
                Logger.getLogger(Connect4.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(Connect4.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    //if game is started allows to cancel
    private void jButton65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton65ActionPerformed
        if (startGame == true) {
            try {
                cancelGame();
            } catch (NoSuchFieldException ex) {
                Logger.getLogger(Connect4.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalArgumentException ex) {
                Logger.getLogger(Connect4.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(Connect4.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton65ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Connect4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Connect4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Connect4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Connect4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Connect4().setVisible(true);
            }
        });
    }
    /*
    checkForWin()       goes over grid for win condition
    precondition        starGame=true
    param string board  contains string of X,O,and Y. 
    param buttonArray   2D array of grid
    param move          keeps tally of total moves played
    postcondition       player wins game
    */
    private void checkForWin() throws NoSuchFieldException, IllegalArgumentException, IllegalAccessException {
        System.out.println(board);

        // all rows
        for (int row = 0; row < 8; row++) {
            for (int col = 0; col < 8; col++) {
                board += buttonArray[row][col].getText();
                board += ".";
            }
            board += ".";
        }

        //all cols
        for (int col = 0; col < 8; col++) {
            for (int row = 0; row < 8; row++) {
                board += buttonArray[row][col].getText();
                board += ".";
            }
            board += ".";
        }

        //diag NW
        for (int row = 0; row < 8; row++) {
            for (int col = 0; col <= row; col++) {
                int pos = row - col;
                board += buttonArray[pos][col].getText();
                board += ".";
            }
            board += ".";
        }

        //diag SE
        for (int row = 8 - 2; row >= 0; row--) {
            for (int col = 0; col <= row; col++) {
                int pos = row - col;
                board += buttonArray[8 - col - 1][8 - pos - 1].getText();
                board += ".";
            }
            board += ".";

        }

        //row 0
        board += jButton1.getText();
        board += jButton2.getText();
        board += jButton3.getText();
        board += jButton4.getText();
        board += jButton5.getText();
        board += jButton6.getText();
        board += jButton7.getText();
        board += jButton8.getText();
        board += ".";

        //row 1
        board += jButton9.getText();
        board += jButton10.getText();
        board += jButton11.getText();
        board += jButton12.getText();
        board += jButton13.getText();
        board += jButton14.getText();
        board += jButton15.getText();
        board += jButton16.getText();
        board += ".";

        // row 2
        board += jButton17.getText();
        board += jButton18.getText();
        board += jButton19.getText();
        board += jButton20.getText();
        board += jButton21.getText();
        board += jButton22.getText();
        board += jButton23.getText();
        board += jButton24.getText();
        board += ".";

        // row 3    
        board += jButton25.getText();
        board += jButton26.getText();
        board += jButton27.getText();
        board += jButton28.getText();
        board += jButton29.getText();
        board += jButton30.getText();
        board += jButton31.getText();
        board += jButton32.getText();
        board += ".";

        // row 4
        board += jButton33.getText();
        board += jButton34.getText();
        board += jButton35.getText();
        board += jButton36.getText();
        board += jButton37.getText();
        board += jButton38.getText();
        board += jButton39.getText();
        board += jButton40.getText();
        board += ".";

        // row 5
        board += jButton41.getText();
        board += jButton42.getText();
        board += jButton43.getText();
        board += jButton44.getText();
        board += jButton45.getText();
        board += jButton46.getText();
        board += jButton47.getText();
        board += jButton48.getText();
        board += ".";

        // row 6
        board += jButton49.getText();
        board += jButton50.getText();
        board += jButton51.getText();
        board += jButton52.getText();
        board += jButton53.getText();
        board += jButton54.getText();
        board += jButton55.getText();
        board += jButton56.getText();
        board += ".";

        // row 7
        board += jButton57.getText();
        board += jButton58.getText();
        board += jButton59.getText();
        board += jButton60.getText();
        board += jButton61.getText();
        board += jButton62.getText();
        board += jButton63.getText();
        board += jButton64.getText();
        board += ".";

        //col 0
        board += jButton1.getText();
        board += jButton9.getText();
        board += jButton17.getText();
        board += jButton25.getText();
        board += jButton33.getText();
        board += jButton41.getText();
        board += jButton49.getText();
        board += jButton57.getText();
        board += ".";

        //col  1
        board += jButton2.getText();
        board += jButton10.getText();
        board += jButton18.getText();
        board += jButton26.getText();
        board += jButton34.getText();
        board += jButton42.getText();
        board += jButton50.getText();
        board += jButton58.getText();
        board += ".";

        //col 2
        board += jButton3.getText();
        board += jButton11.getText();
        board += jButton19.getText();
        board += jButton27.getText();
        board += jButton35.getText();
        board += jButton43.getText();
        board += jButton51.getText();
        board += jButton59.getText();
        board += ".";

        //col  3    
        board += jButton4.getText();
        board += jButton12.getText();
        board += jButton20.getText();
        board += jButton28.getText();
        board += jButton36.getText();
        board += jButton44.getText();
        board += jButton52.getText();
        board += jButton60.getText();
        board += ".";

        // col  4
        board += jButton5.getText();
        board += jButton13.getText();
        board += jButton21.getText();
        board += jButton29.getText();
        board += jButton37.getText();
        board += jButton45.getText();
        board += jButton53.getText();
        board += jButton61.getText();
        board += ".";

        //col  5
        board += jButton6.getText();
        board += jButton14.getText();
        board += jButton22.getText();
        board += jButton30.getText();
        board += jButton38.getText();
        board += jButton46.getText();
        board += jButton54.getText();
        board += jButton62.getText();
        board += ".";

        // col  6
        board += jButton7.getText();
        board += jButton15.getText();
        board += jButton23.getText();
        board += jButton31.getText();
        board += jButton39.getText();
        board += jButton47.getText();
        board += jButton55.getText();
        board += jButton63.getText();
        board += ".";

        // col  7
        board += jButton8.getText();
        board += jButton16.getText();
        board += jButton24.getText();
        board += jButton32.getText();
        board += jButton40.getText();
        board += jButton48.getText();
        board += jButton56.getText();
        board += jButton64.getText();
        board += ".";

        //diag SE line 0
        board += jButton25.getText();
        board += jButton18.getText();
        board += jButton11.getText();
        board += jButton4.getText();
        board += ".";

        //diag SE line 1
        board += jButton33.getText();
        board += jButton26.getText();
        board += jButton19.getText();
        board += jButton12.getText();
        board += jButton5.getText();
        board += ".";

        //diag SE line 2
        board += jButton41.getText();
        board += jButton34.getText();
        board += jButton27.getText();
        board += jButton20.getText();
        board += jButton13.getText();
        board += jButton6.getText();
        board += ".";

        //diag SE line 3
        board += jButton49.getText();
        board += jButton42.getText();
        board += jButton35.getText();
        board += jButton28.getText();
        board += jButton21.getText();
        board += jButton14.getText();
        board += jButton7.getText();
        board += ".";

        //diag SE line 4
        board += jButton57.getText();
        board += jButton50.getText();
        board += jButton43.getText();
        board += jButton36.getText();
        board += jButton29.getText();
        board += jButton22.getText();
        board += jButton15.getText();
        board += jButton8.getText();
        board += ".";

        //diag SE line 5
        board += jButton58.getText();
        board += jButton51.getText();
        board += jButton44.getText();
        board += jButton37.getText();
        board += jButton30.getText();
        board += jButton23.getText();
        board += jButton16.getText();
        board += ".";

        //diag SE line 6
        board += jButton59.getText();
        board += jButton52.getText();
        board += jButton45.getText();
        board += jButton38.getText();
        board += jButton31.getText();
        board += jButton24.getText();
        board += ".";

        //diag SE line 7
        board += jButton60.getText();
        board += jButton53.getText();
        board += jButton46.getText();
        board += jButton39.getText();
        board += jButton32.getText();
        board += ".";

        //diag SE line 8
        board += jButton61.getText();
        board += jButton54.getText();
        board += jButton47.getText();
        board += jButton40.getText();
        board += ".";

        //diag SW line 0
        board += jButton32.getText();
        board += jButton23.getText();
        board += jButton14.getText();
        board += jButton5.getText();
        board += ".";

        //diag SW line 1
        board += jButton40.getText();
        board += jButton31.getText();
        board += jButton22.getText();
        board += jButton13.getText();
        board += jButton4.getText();
        board += ".";

        //diag SW line 2
        board += jButton48.getText();
        board += jButton39.getText();
        board += jButton30.getText();
        board += jButton21.getText();
        board += jButton12.getText();
        board += jButton3.getText();
        board += ".";

        //diag SW line 3
        board += jButton56.getText();
        board += jButton47.getText();
        board += jButton38.getText();
        board += jButton29.getText();
        board += jButton20.getText();
        board += jButton11.getText();
        board += jButton2.getText();
        board += ".";

        //diag SW line 4
        board += jButton64.getText();
        board += jButton55.getText();
        board += jButton46.getText();
        board += jButton37.getText();
        board += jButton28.getText();
        board += jButton19.getText();
        board += jButton10.getText();
        board += jButton1.getText();
        board += ".";

        //diag SW line 5
        board += jButton63.getText();
        board += jButton55.getText();
        board += jButton46.getText();
        board += jButton37.getText();
        board += jButton28.getText();
        board += jButton19.getText();
        board += jButton10.getText();
        board += jButton1.getText();
        board += ".";

        //diag SW line 6
        board += jButton62.getText();
        board += jButton53.getText();
        board += jButton44.getText();
        board += jButton35.getText();
        board += jButton26.getText();
        board += jButton17.getText();
        board += ".";

        //diag SW line 7
        board += jButton61.getText();
        board += jButton52.getText();
        board += jButton44.getText();
        board += jButton43.getText();
        board += jButton34.getText();
        board += jButton25.getText();
        board += ".";

        //diag SW line 8
        board += jButton60.getText();
        board += jButton51.getText();
        board += jButton42.getText();
        board += jButton33.getText();
        board += ".";

        if (board.contains(".X.X.X.X.")) {
            JOptionPane.showMessageDialog(this, "Player 1 is the winner");
            cancelGame();
        }

        if (board.contains(".O.O.O.O.")) {
            JOptionPane.showMessageDialog(this, "Player 2 is the winner");
            cancelGame();
        }

        if (board.contains(".Y.Y.Y.Y.")) {
            JOptionPane.showMessageDialog(this, "Player 3 is the winner");
            cancelGame();
        }

        if (move == 64) {
            JOptionPane.showMessageDialog(this, "There is a draw");
            cancelGame();
        }
    }

    
    /*
    clearBoard()    clears grid
    param buttonArray   2D array of grid
    */
    private void clearBoard() throws NoSuchFieldException, IllegalArgumentException, IllegalAccessException {

        for (int row = 0; row < 8; row++) {
            for (int col = 0; col < 8; col++) {
                buttonArray[row][col].setText("");
                buttonArray[row][col].setBackground(Color.white);
            }
        }
    }

    /*
    cancelGame()    sets everything to pre startbutton conditions
    */
    private void cancelGame() throws NoSuchFieldException, IllegalArgumentException, IllegalAccessException {

        clearBoard();
        disableButtons();
        enableColorButton();
        startButton.setText("Start Game");
        p1 = true;
        p2 = false;
        p3 = false;
        board = "";
        move = 0;

    }

    //disables grid
    private void disableButtons() {

        for (int row = 0; row < 8; row++) {
            for (int col = 0; col < 8; col++) {
                buttonArray[row][col].setEnabled(false);
            }

        }
    }

    //enables grid
    private void enableButtons() {

        for (int row = 0; row < 8; row++) {
            for (int col = 0; col < 8; col++) {
                buttonArray[row][col].setEnabled(true);
            }

        }
    }
    
    //disables color combo buttons
    private void disableColorButton() {
        jComboBox1.setEnabled(false);
        jComboBox2.setEnabled(false);
        jComboBox3.setEnabled(false);
    }

    //enables color combo buttons
    private void enableColorButton() {
        jComboBox1.setEnabled(true);
        jComboBox2.setEnabled(true);
        jComboBox3.setEnabled(true);
    }

    //variables
    //board starts empty
    String board = "";
    //start game starts false
    boolean startGame = false;
    //default player order. p1 starts
    boolean p1 = true;
    boolean p2 = false;
    boolean p3 = false;
    //default player color is red
    int p1Color = 1;
    int p2Color = 1;
    int p3Color = 1;
    //total moves
    int move;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel playerPanel;
    private javax.swing.JButton startButton;
    private javax.swing.JPanel topPanel;
    private javax.swing.JPanel topTopPanel;
    // End of variables declaration//GEN-END:variables
}
